'use server';

import { selectWord } from '@/ai/flows/select-word';

/**
 * Gets a new word for the Hangman game using an AI model.
 * The difficulty of the word is adjusted based on the player's win/loss ratio.
 * @param winLossRatio - The ratio of wins to losses for the current player.
 * @returns A promise that resolves to the new word in uppercase.
 */
export async function getNewWord(winLossRatio: number, wordList: string[]): Promise<string> {
  try {
    const result = await selectWord({ winLossRatio }, wordList);
    if (!result.word || result.word.trim() === '' || !/^[a-zA-Z]+$/.test(result.word)) {
        throw new Error('AI returned an invalid word.');
    }
    // The word should be uppercase for easier comparison and display consistency.
    return result.word.toUpperCase();
  } catch (error) {
    console.error("Failed to get a new word from AI, providing a fallback.", error);
    // Provide a fallback word list in case the AI service is unavailable or fails.
    const fallbackWords = ["action", "active", "actual", "advice", "affect", "afraid", "agency", "agenda",
  "almost", "always", "amount", "animal", "annual", "answer", "anyone", "apart",
  "appeal", "appear", "around", "arrive", "artist", "aspect", "assess", "assist",
  "assume", "attack", "attend", "august", "author", "avenue", "backed", "battle",
  "beauty", "became", "become", "before", "behind", "belief", "belong", "beside",
  "better", "beyond", "bishop", "border", "bottle", "bottom", "bought", "branch",
  "breath", "bridge", "bright", "broken", "budget", "burden", "bureau", "button",
  "camera", "cancer", "cannot", "carbon", "career", "castle", "casual", "caught",
  "center", "chance", "change", "charge", "choice", "choose", "church", "circle",
  "client", "closed", "closer", "coffee", "column", "combat", "coming", "common",
  "comply", "copper", "corner", "costly", "county", "couple", "course", "covers",
  "create", "credit", "crisis", "custom", "damage", "danger", "dealer", "debate",
  "decade", "decide", "defeat", "defend", "define", "degree", "demand", "depend",
  "deputy", "desert", "design", "desire", "detail", "detect", "device", "differ",
  "dinner", "direct", "doctor", "dollar", "domain", "double", "driven", "driver",
  "during", "easily", "eating", "editor", "effect", "effort", "eighth", "either",
  "eleven", "emerge", "empire", "employ", "enable", "ending", "energy", "engage",
  "engine", "enough", "ensure", "entire", "entity", "equity", "escape", "estate",
  "ethnic", "exceed", "except", "excess", "expand", "expect", "expert", "export",
  "extend", "extent", "fabric", "facing", "factor", "failed", "fairly", "fallen",
  "family", "famous", "father", "faulty", "favour", "fellow", "female", "figure",
  "filing", "finger", "finish", "fiscal", "flight", "flying", "follow", "forced",
  "forest", "forget", "formal", "format", "former", "foster", "fought", "fourth",
  "freely", "friend", "future", "garden", "gather", "gender", "german", "global",
  "golden", "ground", "growth", "guilty", "handed", "handle", "happen", "hardly",
  "headed", "health", "height", "hidden", "holder", "honest", "impact", "import",
  "income", "indeed", "injury", "inside", "intend", "intent", "invest", "island",
  "itself", "jersey", "joseph", "junior", "killed", "labour", "latest", "latter",
  "launch", "lawyer", "leader", "league", "leaves", "legacy", "length", "lesson",
  "letter", "lights", "likely", "linked", "liquid", "listen", "little", "living",
  "losing", "lucent", "luxury", "mainly", "manage", "manner", "manual", "margin",
  "marine", "marked", "market", "martin", "master", "matter", "medium", "member",
  "memory", "mental", "merely", "method", "middle", "miller", "mining", "minute",
  "mirror", "mobile", "modern", "modest", "module", "moment", "morris", "mostly",
  "mother", "motion", "moving", "murder", "museum", "mutual", "myself", "narrow",
  "nation", "native", "nature", "nearby", "nearly", "nights", "nobody", "normal",
  "notice", "notion", "number", "object", "obtain", "office", "offset", "online",
  "option", "orange", "origin", "output", "oxford", "packed", "palace", "parent",
  "partly", "patent", "people", "period", "permit", "person", "phrase", "picked",
  "planet", "player", "please", "plenty", "pocket", "police", "policy", "prefer",
  "pretty", "prince", "prison", "profit", "proper", "proven", "public", "pursue",
  "raised", "random", "rarely", "rather", "rating", "reader", "really", "reason",
  "recall", "recent", "record", "reduce", "reform", "regard", "regime", "region",
  "relate", "relief", "remain", "remote", "remove", "repair", "repeat", "replay",
  "report", "rescue", "resort", "result", "retail", "retain", "return", "reveal",
  "review", "reward", "riding", "rising", "robust", "ruling", "safety", "salary",
  "sample", "saving", "saying", "scheme", "school", "screen", "search", "season",
  "second", "secret", "sector", "secure", "seeing", "select", "seller", "senior",
  "series", "server", "settle", "severe", "sexual", "should", "signal", "signed",
  "silent", "silver", "simple", "simply", "single", "sister", "slight", "smooth",
  "social", "solely", "sought", "source", "soviet", "speech", "spirit", "spoken",
  "spread", "spring", "square", "stable", "status", "steady", "stolen", "strain",
  "stream", "street", "stress", "strict", "strike", "string", "strong", "struck",
  "studio", "submit", "sudden", "suffer", "summer", "summit", "supply", "surely",
  "survey", "switch", "symbol", "system", "taking", "talent", "target", "taught",
  "tenant", "tender", "tennis", "thanks", "theory", "thirty", "though", "threat",
  "thrown", "ticket", "timely", "timing", "tissue", "toward", "travel", "treaty",
  "trying", "twelve", "twenty", "unable", "unique", "united", "unless", "unlike",
  "update", "useful", "valley", "varied", "vendor", "versus", "victim", "vision",
  "visual", "volume", "walker", "wealth", "weekly", "weight", "wholly", "window",
  "winner", "winter", "within", "wonder", "worker", "wright", "writer", "yellow",
  "yields",

  // 7+ Letters
  "abandoned", "absolute", "abstract", "academic", "accident", "accurate",
  "achieved", "acquired", "activity", "actually", "addition", "adequate",
  "adjacent", "adjusted", "advanced", "advisory", "advocate", "affected",
  "aircraft", "alliance", "although", "ambition", "analysis", "announce",
  "anything", "anywhere", "apparent", "appendix", "approach", "approval",
  "argument", "artistic", "assigned", "assistant", "associate", "assumed",
  "athletic", "attached", "attitude", "attorney", "audience", "autonomy",
  "available", "awareness", "baseball", "beautiful", "beginning", "benchmark",
  "beneath", "beneficial", "biblical", "bilingual", "brother", "building",
  "business", "calendar", "campaign", "capacity", "capital", "capture",
  "carefully", "carriage", "category", "Catholic", "cautious", "celebrity",
  "certain", "chairman", "champion", "chemical", "civilian", "classical",
  "clinical", "clothing", "collapse", "colonial", "colorful", "commander",
  "commerce", "commonly", "compared", "compete", "complete", "composed",
  "compound", "comprise", "computer", "concept", "concerned", "concert",
  "conclude", "concrete", "conflict", "confused", "congress", "consider",
  "constant", "consumer", "continue", "contract", "contrary", "contrast",
  "convince", "corridor", "coverage", "creation", "creative", "creature",
  "criminal", "critical", "cultural", "currency", "customer", "darkness",
  "database", "daughter", "daylight", "deadline", "decade", "december",
  "decision", "decrease", "defendant", "definite", "delivery", "democracy",
  "dependent", "designer", "detailed", "development", "devoted", "diameter",
  "dimension", "directly", "disaster", "discover", "distance", "distinct",
  "district", "document", "domestic", "dominant", "dominate", "doubtful",
  "dramatic", "dressed", "drinking", "dropped", "duration", "dynamics",
  "earnings", "economic", "educated", "effective", "efficient", "elderly",
  "election", "electric", "eligible", "emerging", "emphasis", "employee",
  "employer", "engineer", "enormous", "entirely", "entrance", "envelope",
  "equality", "equation", "equipped", "essential", "establish", "estimate",
  "evaluate", "everyday", "everyone", "evidence", "exchange", "exciting",
  "exercise", "existing", "expansion", "expected", "explicit", "explore",
  "exposure", "extended", "external", "facility", "familiar", "favorite",
  "feedback", "festival", "finished", "firewall", "flagship", "flexible",
  "football", "forecast", "formerly", "fourteen", "fraction", "frequent",
  "friendly", "frontier", "function", "generate", "generous", "genetics",
  "genuine", "goodwill", "governor", "graduate", "graphics", "guardian",
  "guidance", "handling", "hardware", "heritage", "highlight", "historic",
  "homeless", "homepage", "honestly", "horizon", "hospital", "humanity",
  "identify", "identity", "ideology", "imperial", "incident", "included",
  "increase", "indicate", "industry", "informal", "informed", "injury",
  "innocent", "inspired", "instance", "integral", "intended", "interact",
  "interest", "interior", "internal", "interval", "intimate", "invasion",
  "involved", "isolated", "judgment", "judicial", "junction", "keyboard",
  "landlord", "language", "laughter", "learning", "leverage", "lifetime",
  "lighting", "likewise", "limitation", "listening", "literary", "location",
  "magazine", "magnetic", "maintain", "majority", "management", "manufacture",
  "marriage", "material", "mathematics", "meaning", "measure", "mechanism",
  "medicine", "mentioned", "merchant", "midnight", "military", "minimize",
  "ministry", "minority", "mobility", "modeling", "moderate", "momentum",
  "monetary", "moreover", "mortgage", "mountain", "movement", "multiple",
  "musician", "narrative", "narrowly", "national", "negative", "neighbor",
  "nominate", "northern", "notebook", "nothing", "novelist", "nowhere",
  "nuclear", "numerous", "objective", "obligation", "observer", "obtained",
  "occasion", "offense", "official", "offshore", "operator", "opponent",
  "opposite", "optimism", "ordinary", "organize", "original", "outcome",
  "outdoor", "outline", "outlook", "output", "overcome", "overhead",
  "overseas", "overview", "painting", "parallel", "parental", "participate",
  "particle", "passage", "passenger", "patience", "peaceful", "penalty",
  "pension", "perceive", "percent", "perfect", "perform", "periodic",
  "permanent", "personal", "persuade", "petition", "physical", "pipeline",
  "platform", "pleasant", "pleasure", "portrait", "position", "positive",
  "possible", "powerful", "practice", "precious", "precise", "predict",
  "premature", "premium", "prepared", "presence", "preserve", "pressure",
  "previous", "princess", "printing", "priority", "prisoner", "private",
  "probable", "proceed", "producer", "professor", "profile", "progress",
  "property", "proposal", "propose", "protect", "protein", "protest",
  "provide", "province", "publicly", "purchase", "pursuant", "quantity",
  "question", "railroad", "randomly", "rapidly", "rational", "reaction",
  "received", "receiver", "recently", "recovery", "regional", "register",
  "regulate", "relation", "relative", "relevant", "reliable", "religion",
  "remember", "repeated", "reporter", "represent", "republic", "required",
  "research", "resemble", "resident", "resistant", "resource", "response",
  "restrict", "retrieve", "revenue", "reviewer", "revision", "rigorous",
  "romantic", "sampling", "scenario", "schedule", "scrutiny", "seasonal",
  "secondly", "security", "sensible", "sentence", "separate", "sequence",
  "sergeant", "severely", "sexually", "shoulder", "simulate", "slightly",
  "software", "solution", "somebody", "somewhat", "southern", "speaker",
  "special", "species", "specific", "spectrum", "spending", "spiritual",
  "standard", "standing", "starting", "statement", "station", "statute",
  "steering", "stimulus", "straight", "strategy", "strength", "striking",
  "structure", "struggle", "suburban", "suddenly", "sufficient", "suggest",
  "superior", "supposed", "surgical", "surprise", "surround", "survival",
  "suspect", "sustain", "swimming", "symbolic", "sympathy", "syndrome",
  "tactical", "targeted", "taxation", "teaching", "tendency", "terminal",
  "terrible", "terrific", "territory", "textbook", "theology", "theoretical",
  "thinking", "thirteen", "thorough", "thousand", "threaten", "together",
  "tomorrow", "touching", "tracking", "tradition", "training", "transfer",
  "transmit", "traveler", "treasure", "treatment", "triangle", "tropical",
  "turnover", "ultimate", "umbrella", "universe", "unlikely", "upcoming",
  "upstairs", "vacation", "valuable", "variable", "vertical", "victory",
  "violence", "virtually", "visiting", "volunteer", "warranty", "weakness",
  "weighted", "whatever", "whenever", "wherever", "wildlife", "withdraw",
  "workshop", "yourself"];
    return fallbackWords[Math.floor(Math.random() * fallbackWords.length)].toUpperCase();
  }
}
