// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about";
  };
  "./routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/about";
  };
  "./routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "./routes/about/about.tsx": {
    id: "routes/about/about";
    page: "/about";
  };
};